# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if __import__('os').name == 'nt': import win32api; win32api.LoadLibrary('PointCloud2.dll')
if __package__ or '.' in __name__:
    from . import _PointCloud2Wrapper
else:
    import _PointCloud2Wrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PointCloud2Wrapper.delete_SwigPyIterator

    def value(self):
        return _PointCloud2Wrapper.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _PointCloud2Wrapper.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _PointCloud2Wrapper.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _PointCloud2Wrapper.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _PointCloud2Wrapper.SwigPyIterator_equal(self, x)

    def copy(self):
        return _PointCloud2Wrapper.SwigPyIterator_copy(self)

    def next(self):
        return _PointCloud2Wrapper.SwigPyIterator_next(self)

    def __next__(self):
        return _PointCloud2Wrapper.SwigPyIterator___next__(self)

    def previous(self):
        return _PointCloud2Wrapper.SwigPyIterator_previous(self)

    def advance(self, n):
        return _PointCloud2Wrapper.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _PointCloud2Wrapper.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _PointCloud2Wrapper.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _PointCloud2Wrapper.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _PointCloud2Wrapper.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _PointCloud2Wrapper.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _PointCloud2Wrapper.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _PointCloud2Wrapper:
_PointCloud2Wrapper.SwigPyIterator_swigregister(SwigPyIterator)
FASTCDR_VERSION_MAJOR = _PointCloud2Wrapper.FASTCDR_VERSION_MAJOR
FASTCDR_VERSION_MINOR = _PointCloud2Wrapper.FASTCDR_VERSION_MINOR
FASTCDR_VERSION_MICRO = _PointCloud2Wrapper.FASTCDR_VERSION_MICRO
FASTCDR_VERSION_STR = _PointCloud2Wrapper.FASTCDR_VERSION_STR
HAVE_CXX11 = _PointCloud2Wrapper.HAVE_CXX11
FASTCDR_IS_BIG_ENDIAN_TARGET = _PointCloud2Wrapper.FASTCDR_IS_BIG_ENDIAN_TARGET
FASTCDR_HAVE_FLOAT128 = _PointCloud2Wrapper.FASTCDR_HAVE_FLOAT128
FASTCDR_SIZEOF_LONG_DOUBLE = _PointCloud2Wrapper.FASTCDR_SIZEOF_LONG_DOUBLE
import fastdds
class _TimeSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PointCloud2Wrapper.delete__TimeSeq

# Register _TimeSeq in _PointCloud2Wrapper:
_PointCloud2Wrapper._TimeSeq_swigregister(_TimeSeq)
class TimeSeq(_TimeSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _PointCloud2Wrapper.delete_TimeSeq

    def __init__(self, *args):
        _PointCloud2Wrapper.TimeSeq_swiginit(self, _PointCloud2Wrapper.new_TimeSeq(*args))

    def __len__(self):
        return _PointCloud2Wrapper.TimeSeq___len__(self)

    def __getitem__(self, i):
        return _PointCloud2Wrapper.TimeSeq___getitem__(self, i)

# Register TimeSeq in _PointCloud2Wrapper:
_PointCloud2Wrapper.TimeSeq_swigregister(TimeSeq)
class Time(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _PointCloud2Wrapper.delete_Time

    def __init__(self, *args):
        _PointCloud2Wrapper.Time_swiginit(self, _PointCloud2Wrapper.new_Time(*args))

    def __eq__(self, x):
        return _PointCloud2Wrapper.Time___eq__(self, x)

    def __ne__(self, x):
        return _PointCloud2Wrapper.Time___ne__(self, x)

    def sec(self, *args):
        return _PointCloud2Wrapper.Time_sec(self, *args)

    def nanosec(self, *args):
        return _PointCloud2Wrapper.Time_nanosec(self, *args)

# Register Time in _PointCloud2Wrapper:
_PointCloud2Wrapper.Time_swigregister(Time)
FASTDDS_GEN_API_VER = _PointCloud2Wrapper.FASTDDS_GEN_API_VER
class TimePubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _PointCloud2Wrapper.TimePubSubType_swiginit(self, _PointCloud2Wrapper.new_TimePubSubType())
    __swig_destroy__ = _PointCloud2Wrapper.delete_TimePubSubType

    def serialize(self, data, payload, data_representation):
        return _PointCloud2Wrapper.TimePubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _PointCloud2Wrapper.TimePubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _PointCloud2Wrapper.TimePubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _PointCloud2Wrapper.TimePubSubType_compute_key(self, *args)

    def create_data(self):
        return _PointCloud2Wrapper.TimePubSubType_create_data(self)

    def delete_data(self, data):
        return _PointCloud2Wrapper.TimePubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _PointCloud2Wrapper.TimePubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _PointCloud2Wrapper.TimePubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _PointCloud2Wrapper.TimePubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _PointCloud2Wrapper.TimePubSubType_construct_sample(self, memory)

# Register TimePubSubType in _PointCloud2Wrapper:
_PointCloud2Wrapper.TimePubSubType_swigregister(TimePubSubType)
class _HeaderSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PointCloud2Wrapper.delete__HeaderSeq

# Register _HeaderSeq in _PointCloud2Wrapper:
_PointCloud2Wrapper._HeaderSeq_swigregister(_HeaderSeq)
class HeaderSeq(_HeaderSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _PointCloud2Wrapper.delete_HeaderSeq

    def __init__(self, *args):
        _PointCloud2Wrapper.HeaderSeq_swiginit(self, _PointCloud2Wrapper.new_HeaderSeq(*args))

    def __len__(self):
        return _PointCloud2Wrapper.HeaderSeq___len__(self)

    def __getitem__(self, i):
        return _PointCloud2Wrapper.HeaderSeq___getitem__(self, i)

# Register HeaderSeq in _PointCloud2Wrapper:
_PointCloud2Wrapper.HeaderSeq_swigregister(HeaderSeq)
class Header(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _PointCloud2Wrapper.delete_Header

    def __init__(self, *args):
        _PointCloud2Wrapper.Header_swiginit(self, _PointCloud2Wrapper.new_Header(*args))

    def __eq__(self, x):
        return _PointCloud2Wrapper.Header___eq__(self, x)

    def __ne__(self, x):
        return _PointCloud2Wrapper.Header___ne__(self, x)

    def stamp(self, *args):
        return _PointCloud2Wrapper.Header_stamp(self, *args)

    def frame_id(self, *args):
        return _PointCloud2Wrapper.Header_frame_id(self, *args)

# Register Header in _PointCloud2Wrapper:
_PointCloud2Wrapper.Header_swigregister(Header)
class HeaderPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _PointCloud2Wrapper.HeaderPubSubType_swiginit(self, _PointCloud2Wrapper.new_HeaderPubSubType())
    __swig_destroy__ = _PointCloud2Wrapper.delete_HeaderPubSubType

    def serialize(self, data, payload, data_representation):
        return _PointCloud2Wrapper.HeaderPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _PointCloud2Wrapper.HeaderPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _PointCloud2Wrapper.HeaderPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _PointCloud2Wrapper.HeaderPubSubType_compute_key(self, *args)

    def create_data(self):
        return _PointCloud2Wrapper.HeaderPubSubType_create_data(self)

    def delete_data(self, data):
        return _PointCloud2Wrapper.HeaderPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _PointCloud2Wrapper.HeaderPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _PointCloud2Wrapper.HeaderPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _PointCloud2Wrapper.HeaderPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _PointCloud2Wrapper.HeaderPubSubType_construct_sample(self, memory)

# Register HeaderPubSubType in _PointCloud2Wrapper:
_PointCloud2Wrapper.HeaderPubSubType_swigregister(HeaderPubSubType)
class _PointFieldSeq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PointCloud2Wrapper.delete__PointFieldSeq

# Register _PointFieldSeq in _PointCloud2Wrapper:
_PointCloud2Wrapper._PointFieldSeq_swigregister(_PointFieldSeq)
class PointFieldSeq(_PointFieldSeq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _PointCloud2Wrapper.delete_PointFieldSeq

    def __init__(self, *args):
        _PointCloud2Wrapper.PointFieldSeq_swiginit(self, _PointCloud2Wrapper.new_PointFieldSeq(*args))

    def __len__(self):
        return _PointCloud2Wrapper.PointFieldSeq___len__(self)

    def __getitem__(self, i):
        return _PointCloud2Wrapper.PointFieldSeq___getitem__(self, i)

# Register PointFieldSeq in _PointCloud2Wrapper:
_PointCloud2Wrapper.PointFieldSeq_swigregister(PointFieldSeq)
class PointField(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _PointCloud2Wrapper.delete_PointField

    def __init__(self, *args):
        _PointCloud2Wrapper.PointField_swiginit(self, _PointCloud2Wrapper.new_PointField(*args))

    def __eq__(self, x):
        return _PointCloud2Wrapper.PointField___eq__(self, x)

    def __ne__(self, x):
        return _PointCloud2Wrapper.PointField___ne__(self, x)

    def name(self, *args):
        return _PointCloud2Wrapper.PointField_name(self, *args)

    def offset(self, *args):
        return _PointCloud2Wrapper.PointField_offset(self, *args)

    def datatype(self, *args):
        return _PointCloud2Wrapper.PointField_datatype(self, *args)

    def count(self, *args):
        return _PointCloud2Wrapper.PointField_count(self, *args)

# Register PointField in _PointCloud2Wrapper:
_PointCloud2Wrapper.PointField_swigregister(PointField)
cvar = _PointCloud2Wrapper.cvar
INT8 = cvar.INT8
UINT8 = cvar.UINT8
INT16 = cvar.INT16
UINT16 = cvar.UINT16
INT32 = cvar.INT32
UINT32 = cvar.UINT32
FLOAT32 = cvar.FLOAT32
FLOAT64 = cvar.FLOAT64

class PointFieldPubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _PointCloud2Wrapper.PointFieldPubSubType_swiginit(self, _PointCloud2Wrapper.new_PointFieldPubSubType())
    __swig_destroy__ = _PointCloud2Wrapper.delete_PointFieldPubSubType

    def serialize(self, data, payload, data_representation):
        return _PointCloud2Wrapper.PointFieldPubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _PointCloud2Wrapper.PointFieldPubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _PointCloud2Wrapper.PointFieldPubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _PointCloud2Wrapper.PointFieldPubSubType_compute_key(self, *args)

    def create_data(self):
        return _PointCloud2Wrapper.PointFieldPubSubType_create_data(self)

    def delete_data(self, data):
        return _PointCloud2Wrapper.PointFieldPubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _PointCloud2Wrapper.PointFieldPubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _PointCloud2Wrapper.PointFieldPubSubType_is_bounded(self)

    def is_plain(self, data_representation):
        return _PointCloud2Wrapper.PointFieldPubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _PointCloud2Wrapper.PointFieldPubSubType_construct_sample(self, memory)

# Register PointFieldPubSubType in _PointCloud2Wrapper:
_PointCloud2Wrapper.PointFieldPubSubType_swigregister(PointFieldPubSubType)
class PointField_vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _PointCloud2Wrapper.PointField_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _PointCloud2Wrapper.PointField_vector___nonzero__(self)

    def __bool__(self):
        return _PointCloud2Wrapper.PointField_vector___bool__(self)

    def __len__(self):
        return _PointCloud2Wrapper.PointField_vector___len__(self)

    def __getslice__(self, i, j):
        return _PointCloud2Wrapper.PointField_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _PointCloud2Wrapper.PointField_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _PointCloud2Wrapper.PointField_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _PointCloud2Wrapper.PointField_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _PointCloud2Wrapper.PointField_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _PointCloud2Wrapper.PointField_vector___setitem__(self, *args)

    def pop(self):
        return _PointCloud2Wrapper.PointField_vector_pop(self)

    def append(self, x):
        return _PointCloud2Wrapper.PointField_vector_append(self, x)

    def empty(self):
        return _PointCloud2Wrapper.PointField_vector_empty(self)

    def size(self):
        return _PointCloud2Wrapper.PointField_vector_size(self)

    def swap(self, v):
        return _PointCloud2Wrapper.PointField_vector_swap(self, v)

    def begin(self):
        return _PointCloud2Wrapper.PointField_vector_begin(self)

    def end(self):
        return _PointCloud2Wrapper.PointField_vector_end(self)

    def rbegin(self):
        return _PointCloud2Wrapper.PointField_vector_rbegin(self)

    def rend(self):
        return _PointCloud2Wrapper.PointField_vector_rend(self)

    def clear(self):
        return _PointCloud2Wrapper.PointField_vector_clear(self)

    def get_allocator(self):
        return _PointCloud2Wrapper.PointField_vector_get_allocator(self)

    def pop_back(self):
        return _PointCloud2Wrapper.PointField_vector_pop_back(self)

    def erase(self, *args):
        return _PointCloud2Wrapper.PointField_vector_erase(self, *args)

    def __init__(self, *args):
        _PointCloud2Wrapper.PointField_vector_swiginit(self, _PointCloud2Wrapper.new_PointField_vector(*args))

    def push_back(self, x):
        return _PointCloud2Wrapper.PointField_vector_push_back(self, x)

    def front(self):
        return _PointCloud2Wrapper.PointField_vector_front(self)

    def back(self):
        return _PointCloud2Wrapper.PointField_vector_back(self)

    def assign(self, n, x):
        return _PointCloud2Wrapper.PointField_vector_assign(self, n, x)

    def resize(self, *args):
        return _PointCloud2Wrapper.PointField_vector_resize(self, *args)

    def insert(self, *args):
        return _PointCloud2Wrapper.PointField_vector_insert(self, *args)

    def reserve(self, n):
        return _PointCloud2Wrapper.PointField_vector_reserve(self, n)

    def capacity(self):
        return _PointCloud2Wrapper.PointField_vector_capacity(self)
    __swig_destroy__ = _PointCloud2Wrapper.delete_PointField_vector

# Register PointField_vector in _PointCloud2Wrapper:
_PointCloud2Wrapper.PointField_vector_swigregister(PointField_vector)
class uint8_t_vector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _PointCloud2Wrapper.uint8_t_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _PointCloud2Wrapper.uint8_t_vector___nonzero__(self)

    def __bool__(self):
        return _PointCloud2Wrapper.uint8_t_vector___bool__(self)

    def __len__(self):
        return _PointCloud2Wrapper.uint8_t_vector___len__(self)

    def __getslice__(self, i, j):
        return _PointCloud2Wrapper.uint8_t_vector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _PointCloud2Wrapper.uint8_t_vector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _PointCloud2Wrapper.uint8_t_vector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _PointCloud2Wrapper.uint8_t_vector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _PointCloud2Wrapper.uint8_t_vector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _PointCloud2Wrapper.uint8_t_vector___setitem__(self, *args)

    def pop(self):
        return _PointCloud2Wrapper.uint8_t_vector_pop(self)

    def append(self, x):
        return _PointCloud2Wrapper.uint8_t_vector_append(self, x)

    def empty(self):
        return _PointCloud2Wrapper.uint8_t_vector_empty(self)

    def size(self):
        return _PointCloud2Wrapper.uint8_t_vector_size(self)

    def swap(self, v):
        return _PointCloud2Wrapper.uint8_t_vector_swap(self, v)

    def begin(self):
        return _PointCloud2Wrapper.uint8_t_vector_begin(self)

    def end(self):
        return _PointCloud2Wrapper.uint8_t_vector_end(self)

    def rbegin(self):
        return _PointCloud2Wrapper.uint8_t_vector_rbegin(self)

    def rend(self):
        return _PointCloud2Wrapper.uint8_t_vector_rend(self)

    def clear(self):
        return _PointCloud2Wrapper.uint8_t_vector_clear(self)

    def get_allocator(self):
        return _PointCloud2Wrapper.uint8_t_vector_get_allocator(self)

    def pop_back(self):
        return _PointCloud2Wrapper.uint8_t_vector_pop_back(self)

    def erase(self, *args):
        return _PointCloud2Wrapper.uint8_t_vector_erase(self, *args)

    def __init__(self, *args):
        _PointCloud2Wrapper.uint8_t_vector_swiginit(self, _PointCloud2Wrapper.new_uint8_t_vector(*args))

    def push_back(self, x):
        return _PointCloud2Wrapper.uint8_t_vector_push_back(self, x)

    def front(self):
        return _PointCloud2Wrapper.uint8_t_vector_front(self)

    def back(self):
        return _PointCloud2Wrapper.uint8_t_vector_back(self)

    def assign(self, n, x):
        return _PointCloud2Wrapper.uint8_t_vector_assign(self, n, x)

    def resize(self, *args):
        return _PointCloud2Wrapper.uint8_t_vector_resize(self, *args)

    def insert(self, *args):
        return _PointCloud2Wrapper.uint8_t_vector_insert(self, *args)

    def reserve(self, n):
        return _PointCloud2Wrapper.uint8_t_vector_reserve(self, n)

    def capacity(self):
        return _PointCloud2Wrapper.uint8_t_vector_capacity(self)

    def get_buffer(self):
        return _PointCloud2Wrapper.uint8_t_vector_get_buffer(self)
    __swig_destroy__ = _PointCloud2Wrapper.delete_uint8_t_vector

# Register uint8_t_vector in _PointCloud2Wrapper:
_PointCloud2Wrapper.uint8_t_vector_swigregister(uint8_t_vector)
class _PointCloud2Seq(fastdds.LoanableCollection):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PointCloud2Wrapper.delete__PointCloud2Seq

# Register _PointCloud2Seq in _PointCloud2Wrapper:
_PointCloud2Wrapper._PointCloud2Seq_swigregister(_PointCloud2Seq)
class PointCloud2Seq(_PointCloud2Seq):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _PointCloud2Wrapper.delete_PointCloud2Seq

    def __init__(self, *args):
        _PointCloud2Wrapper.PointCloud2Seq_swiginit(self, _PointCloud2Wrapper.new_PointCloud2Seq(*args))

    def __len__(self):
        return _PointCloud2Wrapper.PointCloud2Seq___len__(self)

    def __getitem__(self, i):
        return _PointCloud2Wrapper.PointCloud2Seq___getitem__(self, i)

# Register PointCloud2Seq in _PointCloud2Wrapper:
_PointCloud2Wrapper.PointCloud2Seq_swigregister(PointCloud2Seq)
class PointCloud2(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _PointCloud2Wrapper.delete_PointCloud2

    def __init__(self, *args):
        _PointCloud2Wrapper.PointCloud2_swiginit(self, _PointCloud2Wrapper.new_PointCloud2(*args))

    def __eq__(self, x):
        return _PointCloud2Wrapper.PointCloud2___eq__(self, x)

    def __ne__(self, x):
        return _PointCloud2Wrapper.PointCloud2___ne__(self, x)

    def header(self, *args):
        return _PointCloud2Wrapper.PointCloud2_header(self, *args)

    def height(self, *args):
        return _PointCloud2Wrapper.PointCloud2_height(self, *args)

    def width(self, *args):
        return _PointCloud2Wrapper.PointCloud2_width(self, *args)

    def fields(self, *args):
        return _PointCloud2Wrapper.PointCloud2_fields(self, *args)

    def is_bigendian(self, *args):
        return _PointCloud2Wrapper.PointCloud2_is_bigendian(self, *args)

    def point_step(self, *args):
        return _PointCloud2Wrapper.PointCloud2_point_step(self, *args)

    def row_step(self, *args):
        return _PointCloud2Wrapper.PointCloud2_row_step(self, *args)

    def data(self, *args):
        return _PointCloud2Wrapper.PointCloud2_data(self, *args)

    def is_dense(self, *args):
        return _PointCloud2Wrapper.PointCloud2_is_dense(self, *args)

# Register PointCloud2 in _PointCloud2Wrapper:
_PointCloud2Wrapper.PointCloud2_swigregister(PointCloud2)
class PointCloud2PubSubType(fastdds.TopicDataType):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _PointCloud2Wrapper.PointCloud2PubSubType_swiginit(self, _PointCloud2Wrapper.new_PointCloud2PubSubType())
    __swig_destroy__ = _PointCloud2Wrapper.delete_PointCloud2PubSubType

    def serialize(self, data, payload, data_representation):
        return _PointCloud2Wrapper.PointCloud2PubSubType_serialize(self, data, payload, data_representation)

    def deserialize(self, payload, data):
        return _PointCloud2Wrapper.PointCloud2PubSubType_deserialize(self, payload, data)

    def calculate_serialized_size(self, data, data_representation):
        return _PointCloud2Wrapper.PointCloud2PubSubType_calculate_serialized_size(self, data, data_representation)

    def compute_key(self, *args):
        return _PointCloud2Wrapper.PointCloud2PubSubType_compute_key(self, *args)

    def create_data(self):
        return _PointCloud2Wrapper.PointCloud2PubSubType_create_data(self)

    def delete_data(self, data):
        return _PointCloud2Wrapper.PointCloud2PubSubType_delete_data(self, data)

    def register_type_object_representation(self):
        return _PointCloud2Wrapper.PointCloud2PubSubType_register_type_object_representation(self)

    def is_bounded(self):
        return _PointCloud2Wrapper.PointCloud2PubSubType_is_bounded(self)

    @staticmethod
    def is_zerocopy():
        return _PointCloud2Wrapper.PointCloud2PubSubType_is_zerocopy()

    def is_plain(self, data_representation):
        return _PointCloud2Wrapper.PointCloud2PubSubType_is_plain(self, data_representation)

    def construct_sample(self, memory):
        return _PointCloud2Wrapper.PointCloud2PubSubType_construct_sample(self, memory)

# Register PointCloud2PubSubType in _PointCloud2Wrapper:
_PointCloud2Wrapper.PointCloud2PubSubType_swigregister(PointCloud2PubSubType)

